### ISSUE TITLE
ConvperPos.py fails to write *_PosTag.csv

### ISSUE THREAD

**Issue by evgnt** [sandberg-lab/NASC-seq#12]
Hi there, could you please have a look again in the code of ConvperPos.py? It seems there is a typo in line 42; if `len(ContigLocs[key][k]) == 1:` works if corrected to "`if len(ContigLocs[key]) == 1:`", but then it stalls in ExportasVcf(). Running with Example data P1_A06_S6 and P1_A09_S9, fails to write *_PosTag.csv. (bam files are tagged and it writes *PositionTagged.bam files). Error:

ValueError: Length mismatch: Expected axis has 0 elements, new values have 1 elements
Traceback (most recent call last):
  ```
File "NASC-seq/scripts/ConvperPos.py", line 201, in <module>
    A=ExportasVcf(ConvsPerPos,CoverofPosWithConvs,AnnoteLocs)
  File "NASC-seq/scripts/ConvperPos.py", line 74, in ExportasVcf
    df.columns = ['convs'] 
```

thnx

**Comment by yiyisun682** [comment]
I got the same error when I ran the conversiontag step. The errors are as follows:

Traceback (most recent call last):
  File "./scripts/ConvperPos.py", line 201, in <module>
    A=ExportasVcf(ConvsPerPos,CoverofPosWithConvs,AnnoteLocs)
  File "./scripts/ConvperPos.py", line 74, in ExportasVcf
    df.columns = ['convs']
  File "./anaconda2/envs/nasc-py2/lib/python2.7/site-packages/pandas/core/generic.py", line 4389, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "./anaconda2/envs/nasc-py2/lib/python2.7/site-packages/pandas/core/generic.py", line 646, in _set_axis
    self._data.set_axis(axis, labels)
  File "./anaconda2/envs/nasc-py2/lib/python2.7/site-packages/pandas/core/internals.py", line 3323, in set_axis
    'values have {new} elements'.format(old=old_len, new=new_len))
ValueError: Length mismatch: Expected axis has 0 elements, new values have 1 elements

**Comment by yiyisun682** [comment]
To test where the error occurred, I print the key (in ConvsPerPos.keys()) and ConvsPerPos[key] in the ConvperPos.py.
The error messages are displayed as follows:

key:
chr18
value:
{47840898L: 1, 9954563L: 35, 59904086L: 165, 9954694L: 34, 47841031L: 1, 31547144L: 127, 9954569L: 35, 59903895L: 409}
key:
ML143360.1
value:
{}
Traceback (most recent call last):
  File "./scripts/ConvperPos.py", line 204, in <module>
    A=ExportasVcf(ConvsPerPos,CoverofPosWithConvs,AnnoteLocs)
  File "./scripts/ConvperPos.py", line 77, in ExportasVcf
    df.columns = ['convs']
  File "./anaconda2/envs/nasc-py2/lib/python2.7/site-packages/pandas/core/generic.py", line 4389, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "./anaconda2/envs/nasc-py2/lib/python2.7/site-packages/pandas/core/generic.py", line 646, in _set_axis
    self._data.set_axis(axis, labels)
  File "./anaconda2/envs/nasc-py2/lib/python2.7/site-packages/pandas/core/internals.py", line 3323, in set_axis
    'values have {new} elements'.format(old=old_len, new=new_len))
ValueError: Length mismatch: Expected axis has 0 elements, new values have 1 elements
Conversions have been added to bamfile tags, and position information has been stored

Hope you can solve this problem.
Thanks

**Comment by evgnt** [comment]
hi there, any progress/help/resolution on this?
many thanks
