### ISSUE TITLE
Error when executing `PECalculation_GJH.py` 

### ISSUE THREAD

**Issue by shayanhoss** [sandberg-lab/NASC-seq#6]
Hello, 

I am setting up the pipeline to run on our Ubuntu server in a `conda env` and am getting an error during the `calculatePE` step of the pipeline. 

Command: 
```(base) shayanhoss@ndnd:~/ExperimentDir$ python2.7 ~/code/NASC-seq/NASCseq_pipeline_pe_v2.py -e ~/ExperimentDir/ -p 24 -f calculatePE```

Output: 
```config.py found in: '/home/shayanhoss/ExperimentDir/config.py'
read length is '100'
verbose is False
Calculating PE for all cells that passed filter...
Calculating error rates for /home/shayanhoss/ExperimentDir/bamFiles/filteredTagged_bam/P1_A09_S9/P1_A09_S9_taggedFiltered.bam
Traceback (most recent call last):
  File "/home/shayanhoss/miniconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3124, in get_value
    return libindex.get_value_box(s, key)
  File "pandas/_libs/index.pyx", line 55, in pandas._libs.index.get_value_box
  File "pandas/_libs/index.pyx", line 63, in pandas._libs.index.get_value_box
TypeError: 'str' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shayanhoss/code/NASC-seq/scripts/PECalculation_GJH.py", line 80, in <module>
    errorRates(bamfilename,outfile,p_e_outfile)
  File "/home/shayanhoss/code/NASC-seq/scripts/PECalculation_GJH.py", line 49, in errorRates
    scperc=sc.filter(regex='a')/tc['a']
  File "/home/shayanhoss/miniconda3/lib/python3.7/site-packages/pandas/core/series.py", line 767, in __getitem__
    result = self.index.get_value(self, key)
  File "/home/shayanhoss/miniconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3132, in get_value
    raise e1
  File "/home/shayanhoss/miniconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3118, in get_value
    tz=getattr(series.dtype, 'tz', None))
  File "pandas/_libs/index.pyx", line 106, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 114, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'a'
Calculating error rates for /home/shayanhoss/ExperimentDir/bamFiles/filteredTagged_bam/P1_A06_S6/P1_A06_S6_taggedFiltered.bam
Traceback (most recent call last):
  File "/home/shayanhoss/miniconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3124, in get_value
    return libindex.get_value_box(s, key)
  File "pandas/_libs/index.pyx", line 55, in pandas._libs.index.get_value_box
  File "pandas/_libs/index.pyx", line 63, in pandas._libs.index.get_value_box
TypeError: 'str' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shayanhoss/code/NASC-seq/scripts/PECalculation_GJH.py", line 80, in <module>
    errorRates(bamfilename,outfile,p_e_outfile)
  File "/home/shayanhoss/code/NASC-seq/scripts/PECalculation_GJH.py", line 49, in errorRates
    scperc=sc.filter(regex='a')/tc['a']
  File "/home/shayanhoss/miniconda3/lib/python3.7/site-packages/pandas/core/series.py", line 767, in __getitem__
    result = self.index.get_value(self, key)
  File "/home/shayanhoss/miniconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3132, in get_value
    raise e1
  File "/home/shayanhoss/miniconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3118, in get_value
    tz=getattr(series.dtype, 'tz', None))
  File "pandas/_libs/index.pyx", line 106, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 114, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
```

Something about the way the `errorRates` function is  seeing `a` as a str and not as a regex.

Please advise how to amend this. The only thing different is that I am using `pysam` for a python3.7 from PyPI but that doesnt seem to be where the error starts.

Thanks

**Comment by shayanhoss** [comment]
@gjhendriks any help here?

**Comment by AntonJMLarsson** [comment]
Can you please show me the head of the bam file in the error message? I would like to see the tags.

**Comment by shayanhoss** [comment]
Well that would explain something.... the bam file is empty. So upsteam issue still :/

**Comment by gjhendriks** [comment]
If you find out at which step the BAM files no longer process well and you would like some input on that please open a new issue.
